export const DEFAULT_AUTHENTICATED_PATH = '/legal/ai-assistant'
export const PLATFORM_KNOWLEDGE_BASES_PATH = '/platform/knowledge-bases'

export const LEGAL_ASSISTANT_HOME_ROUTE = 'legalAssistantHome'
export const LEGAL_ASSISTANT_CHAT_ROUTE = 'legalAssistantChat'
export const LEGAL_CONTRACT_REVIEW_ROUTE = 'legalContractReview'
export const LEGAL_CONTRACT_REVIEW_DETAIL_ROUTE = 'legalContractReviewDetail'
export const LEGAL_SMART_ARCHIVE_ROUTE = 'legalSmartArchive'
export const LEGAL_DOCUMENT_DRAFTING_ROUTE = 'legalDocumentDrafting'
export const LEGAL_DOCUMENT_DRAFTING_DETAIL_ROUTE = 'legalDocumentDraftingDetail'
export const LEGAL_DOCUMENT_DRAFTING_DEBUG_ROUTE = 'legalDocumentDraftingDebug'
