<template>
  <section class="review-list">
    <header class="review-list__header"><div><span>{{ t('contractReview.workspaceEyebrow') }}</span><h1>{{ t('contractReview.title') }}</h1><p>{{ t('contractReview.subtitle') }}</p></div><button type="button" :disabled="creating" @click="newReview"><t-icon name="add" /> {{ t('contractReview.newReview') }}</button></header>
    <nav class="review-list__tabs"><button type="button" :class="{ active: !archived }" @click="setArchived(false)">{{ t('contractReview.active') }}</button><button type="button" :class="{ active: archived }" @click="setArchived(true)">{{ t('contractReview.archived') }}</button></nav>
    <div class="review-list__table">
      <div class="review-list__table-head"><span>{{ t('contractReview.document') }}</span><span>{{ t('contractReview.statusLabel') }}</span><span>{{ t('contractReview.party') }}</span><span>{{ t('contractReview.updated') }}</span><span /></div>
      <div v-if="store.loading" class="review-list__empty"><t-loading size="small" /> {{ t('contractReview.loadingReviews') }}</div>
      <div v-else-if="!store.tasks.length" class="review-list__empty"><t-icon name="file-paste" size="28px" /><strong>{{ archived ? t('contractReview.noArchivedReviews') : t('contractReview.noReviews') }}</strong><p>{{ archived ? t('contractReview.noArchivedDescription') : t('contractReview.noReviewsDescription') }}</p></div>
      <article v-for="task in store.tasks" :key="task.id" @click="open(task.id)"><div class="review-name"><i><t-icon name="file-paste" /></i><div><strong>{{ task.title }}</strong><span>{{ task.file_name || t('contractReview.draftNoDocument') }}</span></div></div><span><b class="task-status" :class="`task-status--${task.status}`">{{ t(`contractReview.status.${task.status}`) }}</b></span><span class="muted">{{ t(`contractReview.parties.${task.represented_party}`) }}</span><span class="muted">{{ formatDate(task.updated_at) }}</span><div class="row-actions" @click.stop><button type="button" :title="t('contractReview.rename')" @click="rename(task)"><t-icon name="edit-1" /></button><button type="button" :disabled="isRunning(task.status)" :title="archived ? t('contractReview.unarchive') : t('contractReview.archive')" @click="toggleArchive(task)"><t-icon :name="archived ? 'rollback' : 'archive'" /></button><button type="button" :title="t('contractReview.delete')" @click="remove(task)"><t-icon name="delete" /></button></div></article>
    </div>
  </section>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useI18n } from 'vue-i18n'; import { useRouter } from 'vue-router'; import { Icon as TIcon, Loading as TLoading, MessagePlugin } from 'tdesign-vue-next'
import type { ContractReview, ReviewStatus } from '@/api/contract-review'; import { LEGAL_CONTRACT_REVIEW_DETAIL_ROUTE } from '@/router/paths'; import { useContractReviewStore } from '@/stores/contractReview'
const { t, locale }=useI18n(); const router=useRouter(); const store=useContractReviewStore(); const archived=ref(false); const creating=ref(false)
const load=()=>store.loadList(archived.value).catch((e:any)=>MessagePlugin.error(e?.message||t('contractReview.loadFailed')))
async function newReview(){creating.value=true;try{const task=await store.create();await router.push({name:LEGAL_CONTRACT_REVIEW_DETAIL_ROUTE,params:{reviewId:task.id}})}catch(e:any){MessagePlugin.error(e?.message||t('contractReview.createFailed'))}finally{creating.value=false}}
function open(id:string){router.push({name:LEGAL_CONTRACT_REVIEW_DETAIL_ROUTE,params:{reviewId:id}})} function setArchived(value:boolean){archived.value=value;void load()}
const isRunning=(status:ReviewStatus)=>['uploading','analyzing','reviewing_clauses'].includes(status)
async function rename(task:ContractReview){const value=window.prompt(t('contractReview.renamePrompt'),task.title);if(!value?.trim())return;try{await store.update(task.id,{title:value.trim()});await load()}catch(e:any){MessagePlugin.error(e?.message||t('contractReview.saveFailed'))}}
async function toggleArchive(task:ContractReview){try{await store.update(task.id,{archived:!archived.value});await load()}catch(e:any){MessagePlugin.error(e?.message||t('contractReview.archiveFailed'))}}
async function remove(task:ContractReview){if(!window.confirm(t('contractReview.deleteConfirm',{name:task.title})))return;try{await store.remove(task.id)}catch(e:any){MessagePlugin.error(e?.message||t('contractReview.deleteFailed'))}}
const formatDate=(value:string)=>new Intl.DateTimeFormat(locale.value,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)); onMounted(load)
</script>

<style scoped lang="less">
.review-list{width:100%;height:100%;overflow:auto;padding:42px 48px;background:#f7f7f4;box-sizing:border-box;color:#171715}.review-list__header{max-width:1180px;margin:auto;display:flex;align-items:flex-end;justify-content:space-between;span{font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:#85857e}h1{margin:7px 0 5px;font-size:28px;letter-spacing:-.03em}p{margin:0;color:#6d6d67;font-size:13px}button{height:38px;padding:0 14px;border:0;border-radius:5px;background:#171715;color:#fff;font-weight:650;cursor:pointer}}.review-list__tabs{max-width:1180px;margin:34px auto 0;border-bottom:1px solid #dcdcd7;button{margin-right:22px;padding:0 0 10px;border:0;background:transparent;color:#75756f;font-size:12px;cursor:pointer;&.active{color:#111;font-weight:650;border-bottom:2px solid #111}}}.review-list__table{max-width:1180px;margin:16px auto;background:#fff;border:1px solid #dfdfda;border-radius:6px;overflow:hidden}.review-list__table-head,article{display:grid;grid-template-columns:minmax(300px,2fr) 150px 130px 160px 110px;align-items:center}.review-list__table-head{height:40px;padding:0 16px;background:#f2f2ef;border-bottom:1px solid #dfdfda;color:#85857e;font-size:10px;text-transform:uppercase;letter-spacing:.06em}article{min-height:72px;padding:0 16px;border-bottom:1px solid #ebebe7;cursor:pointer;&:last-child{border:0}&:hover{background:#fafaf8}}.review-name{min-width:0;display:flex;align-items:center;gap:11px;i{width:34px;height:40px;display:flex;align-items:center;justify-content:center;border:1px solid #deded9;border-radius:4px;color:#666;background:#fafaf8}strong,span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}strong{font-size:13px}span{max-width:400px;margin-top:4px;color:#8a8a84;font-size:10px}}.muted{color:#696963;font-size:11px}.task-status{display:inline-flex;padding:4px 7px;border-radius:3px;background:#ededE9;color:#60605a;font-size:10px;font-weight:600;&--analyzing,&--reviewing_clauses{color:#775b1d;background:#f5eedc}&--completed{color:#356147;background:#e7f0ea}&--failed{color:#8b3e34;background:#f6e8e5}}.row-actions{display:flex;justify-content:flex-end;gap:3px;button{width:28px;height:28px;border:0;border-radius:4px;background:transparent;color:#777;cursor:pointer;&:hover{background:#e9e9e5;color:#111}&:disabled{opacity:.3;cursor:not-allowed}}}.review-list__empty{min-height:290px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;color:#85857e;font-size:12px;strong{color:#383834;font-size:13px}p{margin:0}}
</style>
